name: Update Parquet Data from Google Drive

on:
  workflow_dispatch:
    inputs:
      gpkg_file_id:
        description: 'Google Drive File ID of the .gpkg file'
        required: true

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Get a copy of the project code
        uses: actions/checkout@v4

      - name: Step 2 - Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Step 3 - Install system dependencies for GeoPandas
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Step 4 - Install Python packages from our list
        run: pip install -r requirements.txt

      - name: Step 5 - Download the new .gpkg file from Google Drive
        run: gdown --service-account-file '${{ secrets.GDRIVE_CREDENTIALS_DATA }}' --id ${{ inputs.gpkg_file_id }} -O data.gpkg

      - name: Step 6 - Run the conversion script
        run: python streamlinedfileconversion.py data.gpkg

      - name: Step 7 - Save the new Parquet file to the project
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add streamlined_data.parquet
          # The commit command below saves the changes with a message
          git commit -m "Chore: Update Parquet data" || echo "No changes to commit"
          # The push command sends the new file up to GitHub
          git push || echo "No changes to push"