name: Update Management GeoJSON from Google Drive

on:
  repository_dispatch:
    types: [new-habitat-management-gpkg-file]

jobs:
  build-and-commit-management:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install GDAL and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install geopandas
          pip install -r requirements.txt
      
      - name: Install Google API Python Client
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Authenticate to Google Drive
        run: echo '${{ secrets.GDRIVE_CREDENTIALS_DATA }}' > gdrive-credentials.json

      - name: Download .gpkg file from Google Drive
        run: python download_from_gdrive.py "${{ github.event.client_payload.file_id }}" "input-management.gpkg"
      
      - name: Run management conversion script
        run: python habitatmanagementgpkgconversion.py input-management.gpkg data/management_2024-25.geojson

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/management_2024-25.geojson
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Feat: Update management GeoJSON data"
            git push
          fi